/*
  Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
  By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
function problem2(limit: number) {
  let total = 1;
  let prevTotal = 0;
  let sum = 0;
  while (total + prevTotal < limit) {
    let newTotal = total + prevTotal;
    prevTotal = total;
    total = newTotal;
    if (total % 2 === 0) {
      sum = sum + total;
    }
  }
  return sum;
}
console.log(`100: ${problem2(100)}`);
console.log(`4000000: ${problem2(4000000)}`);
